// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrd7WNHeJOk3GBaxC_LtA5A6WvlFZsdew',
    appId: '1:428556533438:web:1f482740e626a4d8c468ef',
    messagingSenderId: '428556533438',
    projectId: 'basic-operations-firebase-app',
    authDomain: 'basic-operations-firebase-app.firebaseapp.com',
    storageBucket: 'basic-operations-firebase-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy1Mr83kPH092HHoHfKvM166Q7NosDOy4',
    appId: '1:428556533438:android:ca8f8908e561b870c468ef',
    messagingSenderId: '428556533438',
    projectId: 'basic-operations-firebase-app',
    storageBucket: 'basic-operations-firebase-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO70kPhSco7QDQJPFBHoCZJeAUQmFdxEs',
    appId: '1:428556533438:ios:2f0a5621d87c2b28c468ef',
    messagingSenderId: '428556533438',
    projectId: 'basic-operations-firebase-app',
    storageBucket: 'basic-operations-firebase-app.appspot.com',
    iosBundleId: 'com.example.basicOperationsFirebase',
  );
}
